### ISSUE TITLE
请问一下read more的按钮和最新文章排在最前要怎么实现, 别打我QAQ

### ISSUE THREAD

**Issue by Mark-ThinkPad** [xaoxuu/hexo.sh#1]
请问一下read more的按钮和最新文章排在最前要怎么实现

**Comment by xaoxuu** [comment]
@Mark-ThinkPad 

## readmore
https://blog.xaoxuu.com/posts/2017-07-05-hexo-blog/#%E5%86%99%E4%B8%8B%E7%AC%AC%E4%B8%80%E7%AF%87%E5%8D%9A%E6%96%87

在文章中间加入
```
<!--more-->
```

## 文章排序
在`_config`中配置
https://github.com/hexojs/hexo-generator-index
